// Package models provides data structures used throughout the application.
package models

import "time"

// LanguageModelProvider represents the LLM provider supported by the application.
type LanguageModelProvider string

const (
	// ProviderCopilot represents the GitHub Copilot Chat API provider
	ProviderCopilot LanguageModelProvider = "copilot"
)

// LanguageModel contains metadata about the Copilot LLM including its capabilities and rate limits.
type LanguageModel struct {
	// ID is the unique identifier for the model
	ID string `json:"id"`
	// Name is the display name for the model
	Name string `json:"name"`
	// Provider indicates which API provider handles this model
	Provider LanguageModelProvider `json:"provider"`
	// MaxRequestsPerMinute is the maximum number of requests allowed per minute
	MaxRequestsPerMinute int `json:"max_requests_per_minute"`
	// MaxTokensPerMinute is the maximum total tokens allowed per minute
	MaxTokensPerMinute int `json:"max_tokens_per_minute"`
	// MaxInputTokensPerMinute is the maximum input tokens allowed per minute
	MaxInputTokensPerMinute int `json:"max_input_tokens_per_minute"`
	// MaxOutputTokensPerMinute is the maximum output tokens allowed per minute
	MaxOutputTokensPerMinute int `json:"max_output_tokens_per_minute"`
	// MaxTokensPerDay is the maximum total tokens allowed per day
	MaxTokensPerDay int `json:"max_tokens_per_day"`
	// Enabled indicates if the model is currently available for use
	Enabled bool `json:"enabled"`
}

// ModelUsage tracks usage metrics for a model to enforce rate limits.
type ModelUsage struct {
	// UserID is the ID of the user the usage belongs to
	UserID uint64 `json:"user_id"`
	// Model is the name of the model being used
	Model string `json:"model"`
	// RequestsThisMinute counts API requests made in the current minute
	RequestsThisMinute int `json:"requests_this_minute"`
	// TokensThisMinute counts total tokens consumed in the current minute
	TokensThisMinute int `json:"tokens_this_minute"`
	// InputTokensThisMinute counts input tokens consumed in the current minute
	InputTokensThisMinute int `json:"input_tokens_this_minute"`
	// OutputTokensThisMinute counts output tokens generated in the current minute
	OutputTokensThisMinute int `json:"output_tokens_this_minute"`
	// TokensThisDay counts total tokens consumed in the current day
	TokensThisDay int `json:"tokens_this_day"`
}

// TokenUsage contains details about token usage for rate limiting.
type TokenUsage struct {
	// Input counts tokens in the user's input
	Input int `json:"input"`
	// Output counts tokens generated by the LLM
	Output int `json:"output"`
}

// ActiveUserCount contains information about active users for resource allocation.
type ActiveUserCount struct {
	// UsersInRecentMinutes is the number of unique users in the past few minutes
	UsersInRecentMinutes int `json:"users_in_recent_minutes"`
	// UsersInRecentDays is the number of unique users in the past few days
	UsersInRecentDays int `json:"users_in_recent_days"`
}

// LLMToken holds claims related to LLM authentication and authorization.
// This represents the decoded content of a JWT used for API authentication.
type LLMToken struct {
	// Iat is the issued at timestamp
	Iat int64 `json:"iat"`
	// Exp is the expiration timestamp
	Exp int64 `json:"exp"`
	// Jti is the JWT ID (unique identifier for the token)
	Jti string `json:"jti"`
	// UserID is the ID of the user the token belongs to
	UserID uint64 `json:"user_id"`
	// GithubUserLogin is the GitHub username of the user
	GithubUserLogin string `json:"github_user_login"`
	// AccountCreatedAt is when the user's account was created
	AccountCreatedAt time.Time `json:"account_created_at"`
	// IsStaff indicates if the user has staff privileges
	IsStaff bool `json:"is_staff"`
	// HasLLMSubscription indicates if the user has a paid subscription
	HasLLMSubscription bool `json:"has_llm_subscription"`
	// MaxMonthlySpendInCents is the maximum allowed spending per month
	MaxMonthlySpendInCents uint32 `json:"max_monthly_spend_in_cents"`
	// CustomMonthlyAllowanceInCents is the custom monthly allowance in cents
	CustomMonthlyAllowanceInCents *uint32 `json:"custom_monthly_allowance_in_cents,omitempty"`
}
